version: '3'
services:
  zap:
    image: justb4/jmeter
    volumes:
      - ../../java-cassandra-app/src/test/jmeter/jmeterTestPlan.jmx:/opt/test/jmeterTestPlan.jmx
    command: -n -t /opt/test/jmeterTestPlan.jmx