apiVersion: v1
kind: Service
metadata:
   name: backend-service
spec:
   selector:
     app: backend-app
   type: NodePort
   ports:
   - name: api
     protocol: TCP
     port: 8085
   - name: db
     protocol: TCP
     port: 27017   
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: backend-deployment
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: backend-app
    spec: 
      containers:
        - name: mongo-db
          image: mongo
          command: ["mongod"]
          args: ["--bind_ip_all"]
          volumeMounts:
            - name: mongodata
              mountPath: "/data/db"
          ports:
            -
              containerPort: 27017
        - name: node-mongo-app
          image: kchandrakant/backend:node-mongo-app
          ports: 
            - 
              containerPort: 8085
      volumes:
        - name: mongodata
          hostPath:
            path: /data/mongo
            type: Directory