---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeless-controller-deployer
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - create
  - get
  - delete
  - list
  - update
  - patch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - create
  - get
  - delete
  - list
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resourceNames:
  - kubeless-registry-credentials
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - kubeless.io
  resources:
  - functions
  - httptriggers
  - cronjobtriggers
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - get
  - delete
  - deletecollection
  - list
  - update
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - get
  - delete
  - list
  - update
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubeless-controller-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeless-controller-deployer
subjects:
- kind: ServiceAccount
  name: controller-acct
  namespace: kubeless
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: functions.kubeless.io
spec:
  group: kubeless.io
  names:
    kind: Function
    plural: functions
    singular: function
  scope: Namespaced
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httptriggers.kubeless.io
spec:
  group: kubeless.io
  names:
    kind: HTTPTrigger
    plural: httptriggers
    singular: httptrigger
  scope: Namespaced
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cronjobtriggers.kubeless.io
spec:
  group: kubeless.io
  names:
    kind: CronJobTrigger
    plural: cronjobtriggers
    singular: cronjobtrigger
  scope: Namespaced
  version: v1beta1
---
apiVersion: v1
data:
  builder-image: kubeless/function-image-builder:v1.0.4
  builder-image-secret: ""
  deployment: '{}'
  enable-build-step: "false"
  function-registry-tls-verify: "true"
  ingress-enabled: "false"
  provision-image: kubeless/unzip@sha256:4863100364496255de9bf8722a220dad7143ab277ac72435876eb8c93936e9d7
  provision-image-secret: ""
  runtime-images: '[{"ID": "ballerina", "depName": "", "fileNameSuffix": ".bal", "versions":
    [{"images": [{"command": "/compile-function.sh $KUBELESS_FUNC_NAME", "image":
    "ballerina/kubeless-ballerina-init@sha256:a04ca9d289c62397d0b493876f6a9ff4cc425563a47aa7e037c3b850b8ceb3e8",
    "phase": "compilation"}, {"image": "ballerina/kubeless-ballerina@sha256:a025841010cfdf8136396efef31d4155283770d331ded6a9003e6e55f02db2e5",
    "phase": "runtime"}], "name": "ballerina0.981.0", "version": "0.981.0"}]}, {"ID":
    "dotnetcore", "depName": "project.csproj", "fileNameSuffix": ".cs", "versions":
    [{"images": [{"command": "/app/compile-function.sh $KUBELESS_INSTALL_VOLUME",
    "image": "allantargino/aspnetcore-build@sha256:0d60f845ff6c9c019362a68b87b3920f3eb2d32f847f2d75e4d190cc0ce1d81c",
    "phase": "compilation"}, {"env": {"DOTNETCORE_HOME": "$(KUBELESS_INSTALL_VOLUME)/packages"},
    "image": "allantargino/kubeless-dotnetcore@sha256:1699b07d9fc0276ddfecc2f823f272d96fd58bbab82d7e67f2fd4982a95aeadc",
    "phase": "runtime"}], "name": "dotnetcore2.0", "version": "2.0"}, {"images": [{"command":
    "/app/compile-function.sh $KUBELESS_INSTALL_VOLUME", "image": "allantargino/aspnetcore-build@sha256:36123cf0279b87c5d27d69558062678a5353cc6db238af46bd5c0e508109f659",
    "phase": "compilation"}, {"env": {"DOTNETCORE_HOME": "$(KUBELESS_INSTALL_VOLUME)/packages"},
    "image": "allantargino/kubeless-dotnetcore@sha256:6d6c659807881e9dac7adde305867163ced5711ef77a3a76e50112bca1ba14cf",
    "phase": "runtime"}], "name": "dotnetcore2.1", "version": "2.1"}]}, {"ID": "go",
    "depName": "Gopkg.toml", "fileNameSuffix": ".go", "versions": [{"images": [{"command":
    "/compile-function.sh", "image": "kubeless/go-init@sha256:03079f4a240bc4eea124327bce22c5ae136a8883b5c047584d923e47f69bd93b",
    "phase": "compilation"}, {"command": "cd $GOPATH/src/kubeless && dep ensure >
    /dev/termination-log 2>&1", "image": "kubeless/go-init@sha256:03079f4a240bc4eea124327bce22c5ae136a8883b5c047584d923e47f69bd93b",
    "phase": "installation"}, {"image": "kubeless/go@sha256:b29724e212a0763db16991f678d1457edb1f6ea4e846c8cbb625c2c4c3308e0f",
    "phase": "runtime"}], "name": "go1.10", "version": "1.10"}, {"images": [{"command":
    "/compile-function.sh", "env": {"GOCACHE": "$(KUBELESS_INSTALL_VOLUME)/.cache"},
    "image": "kubeless/go-init@sha256:f30338225a39d3eec0ba246bd8c67b1919fa9c1c382d43eb96eebeae1aa55be9",
    "phase": "compilation"}, {"command": "cd $GOPATH/src/kubeless && dep ensure >
    /dev/termination-log 2>&1", "env": {"GOCACHE": "$(KUBELESS_INSTALL_VOLUME)/.cache"},
    "image": "kubeless/go-init@sha256:f30338225a39d3eec0ba246bd8c67b1919fa9c1c382d43eb96eebeae1aa55be9",
    "phase": "installation"}, {"image": "kubeless/go@sha256:b29724e212a0763db16991f678d1457edb1f6ea4e846c8cbb625c2c4c3308e0f",
    "phase": "runtime"}], "name": "go1.11", "version": "1.11"}, {"images": [{"command":
    "/compile-function.sh", "env": {"GOCACHE": "$(KUBELESS_INSTALL_VOLUME)/.cache"},
    "image": "kubeless/go-init@sha256:44e442f8b7ac30701bd5233efc1a4d9c2e4e79c5d4c3d09c49399f00793852af",
    "phase": "compilation"}, {"command": "cd $GOPATH/src/kubeless && dep ensure >
    /dev/termination-log 2>&1", "env": {"GOCACHE": "$(KUBELESS_INSTALL_VOLUME)/.cache"},
    "image": "kubeless/go-init@sha256:44e442f8b7ac30701bd5233efc1a4d9c2e4e79c5d4c3d09c49399f00793852af",
    "phase": "installation"}, {"image": "kubeless/go@sha256:b29724e212a0763db16991f678d1457edb1f6ea4e846c8cbb625c2c4c3308e0f",
    "phase": "runtime"}], "name": "go1.12", "version": "1.12"}]}, {"ID": "java", "depName":
    "pom.xml", "fileNameSuffix": ".java", "versions": [{"images": [{"command": "/compile-function.sh",
    "image": "kubeless/java-init@sha256:7e49a9c91e0fd7d0ffd0e184116769e56705cc1d6d39b11ced8ec94dbdc77543",
    "phase": "compilation"}, {"image": "kubeless/java@sha256:fafffa963732c860c08728da99b1ec8c3b722840ac29722e69798124fef63054",
    "phase": "runtime"}], "name": "java1.8", "version": "1.8"}, {"images": [{"command":
    "/compile-function.sh", "image": "kubeless/java-init@sha256:b7a8ae3c17b7cefaa28364348d2f504a02c936d38aee57f46b61f3745c784c17",
    "phase": "compilation"}, {"image": "kubeless/java@sha256:b04e8e1f4a1acb8a94778320df8fd13aaf1eed22034007bf6d9109e55a4aa0c8",
    "phase": "runtime"}], "name": "java11", "version": "11"}]}, {"ID": "nodejs", "depName":
    "package.json", "fileNameSuffix": ".js", "versions": [{"images": [{"command":
    "/kubeless-npm-install.sh", "image": "kubeless/nodejs@sha256:e72370621155aafe904e38e2c382dd3cd5e4058c7ad8baf9bda0d163c001399e",
    "phase": "installation"}, {"env": {"NODE_PATH": "$(KUBELESS_INSTALL_VOLUME)/node_modules"},
    "image": "kubeless/nodejs@sha256:e72370621155aafe904e38e2c382dd3cd5e4058c7ad8baf9bda0d163c001399e",
    "phase": "runtime"}], "name": "node6", "version": "6"}, {"images": [{"command":
    "/kubeless-npm-install.sh", "image": "kubeless/nodejs@sha256:f4b210a7c45730fec888a8ff9ab853405536a361c2526306659c68487528892b",
    "phase": "installation"}, {"env": {"NODE_PATH": "$(KUBELESS_INSTALL_VOLUME)/node_modules"},
    "image": "kubeless/nodejs@sha256:f4b210a7c45730fec888a8ff9ab853405536a361c2526306659c68487528892b",
    "phase": "runtime"}], "name": "node8", "version": "8"}, {"images": [{"command":
    "/kubeless-npm-install.sh", "image": "kubeless/nodejs@sha256:9594e9d601cfe3868b54cccf1cd8763b2430493fed3e06d7dc128a69b263dfaf",
    "phase": "installation"}, {"env": {"NODE_PATH": "$(KUBELESS_INSTALL_VOLUME)/node_modules"},
    "image": "kubeless/nodejs@sha256:9594e9d601cfe3868b54cccf1cd8763b2430493fed3e06d7dc128a69b263dfaf",
    "phase": "runtime"}], "name": "node10", "version": "10"}, {"images": [{"command":
    "/kubeless-npm-install.sh", "image": "kubeless/nodejs@sha256:1c45cda56384adc7deae9bf99e221b8e159ec25980c05b947939096bf91800e6",
    "phase": "installation"}, {"env": {"NODE_PATH": "$(KUBELESS_INSTALL_VOLUME)/node_modules"},
    "image": "kubeless/nodejs@sha256:1c45cda56384adc7deae9bf99e221b8e159ec25980c05b947939096bf91800e6",
    "phase": "runtime"}], "name": "node12", "version": "12"}]}, {"ID": "php", "depName":
    "composer.json", "fileNameSuffix": ".php", "versions": [{"images": [{"command":
    "composer install -d $KUBELESS_INSTALL_VOLUME", "image": "composer:1.6", "phase":
    "installation"}, {"image": "kubeless/php@sha256:981e2bb6b6662176992427d55da76258ecadb0dc9ef03d1feed66250c828014e",
    "phase": "runtime"}], "name": "php72", "version": "7.2"}, {"images": [{"command":
    "composer install -d $KUBELESS_INSTALL_VOLUME", "image": "composer:1.6", "phase":
    "installation"}, {"image": "kubeless/php@sha256:8f7f8aa9980a14126d9b9e8b3742258efd2591b0e152b4d65e0d7b5faf61a041",
    "phase": "runtime"}], "name": "php73", "version": "7.3"}]}, {"ID": "python", "depName":
    "requirements.txt", "fileNameSuffix": ".py", "versions": [{"images": [{"command":
    "pip install --prefix=$KUBELESS_INSTALL_VOLUME -r $KUBELESS_DEPS_FILE", "image":
    "python:2.7", "phase": "installation"}, {"env": {"PYTHONPATH": "$(KUBELESS_INSTALL_VOLUME)/lib/python2.7/site-packages:$(KUBELESS_INSTALL_VOLUME)"},
    "image": "kubeless/python@sha256:7b3cb3c5ff9f2e1cccf22c4a8d6325f21f56fef51ce97c43444de5ff84af428d",
    "phase": "runtime"}], "name": "python27", "version": "2.7"}, {"images": [{"command":
    "pip install --prefix=$KUBELESS_INSTALL_VOLUME -r $KUBELESS_DEPS_FILE", "image":
    "python:3.4", "phase": "installation"}, {"env": {"PYTHONPATH": "$(KUBELESS_INSTALL_VOLUME)/lib/python3.4/site-packages:$(KUBELESS_INSTALL_VOLUME)"},
    "image": "kubeless/python@sha256:f83b37d65825fda1dc6a2105be96e816fc26099538728c319bd6d4ee32b62564",
    "phase": "runtime"}], "name": "python34", "version": "3.4"}, {"images": [{"command":
    "pip install --prefix=$KUBELESS_INSTALL_VOLUME -r $KUBELESS_DEPS_FILE", "image":
    "python:3.6", "phase": "installation"}, {"env": {"PYTHONPATH": "$(KUBELESS_INSTALL_VOLUME)/lib/python3.6/site-packages:$(KUBELESS_INSTALL_VOLUME)"},
    "image": "kubeless/python@sha256:0f0305d7649e622710d939fec7f01d65839131fe58214013323ad9a6db6c0d9f",
    "phase": "runtime"}], "name": "python36", "version": "3.6"}, {"images": [{"command":
    "pip install --prefix=$KUBELESS_INSTALL_VOLUME -r $KUBELESS_DEPS_FILE", "image":
    "python:3.7", "phase": "installation"}, {"env": {"PYTHONPATH": "$(KUBELESS_INSTALL_VOLUME)/lib/python3.7/site-packages:$(KUBELESS_INSTALL_VOLUME)"},
    "image": "kubeless/python@sha256:849bc1c3968783ba15e2cbb1a532f2856c33b7b2c3fbb358ab76e724ecd54bc8",
    "phase": "runtime"}], "name": "python37", "version": "3.7"}]}, {"ID": "ruby",
    "depName": "Gemfile", "fileNameSuffix": ".rb", "versions": [{"images": [{"command":
    "bundle install --gemfile=$KUBELESS_DEPS_FILE --path=$KUBELESS_INSTALL_VOLUME",
    "image": "bitnami/ruby:2.3", "phase": "installation"}, {"env": {"GEM_HOME": "$(KUBELESS_INSTALL_VOLUME)/ruby/2.3.0"},
    "image": "kubeless/ruby@sha256:67870b57adebc4dc749a8a19795da801da2d05fc6e8324168ac1b227bb7c77f7",
    "phase": "runtime"}], "name": "ruby23", "version": "2.3"}, {"images": [{"command":
    "bundle install --gemfile=$KUBELESS_DEPS_FILE --path=$KUBELESS_INSTALL_VOLUME",
    "image": "bitnami/ruby:2.4", "phase": "installation"}, {"env": {"GEM_HOME": "$(KUBELESS_INSTALL_VOLUME)/ruby/2.4.0"},
    "image": "kubeless/ruby@sha256:7bb4c6adb46b31a851ee8940dbffe7619beee09e9d09ef489cebe9ba0c5d8ed2",
    "phase": "runtime"}], "name": "ruby24", "version": "2.4"}, {"images": [{"command":
    "bundle install --gemfile=$KUBELESS_DEPS_FILE --path=$KUBELESS_INSTALL_VOLUME",
    "image": "bitnami/ruby:2.5", "phase": "installation"}, {"env": {"GEM_HOME": "$(KUBELESS_INSTALL_VOLUME)/ruby/2.5.0"},
    "image": "kubeless/ruby@sha256:3a0ede85a3a0735fc826889d45a67251729878b2d3816101d9530b9b655cc622",
    "phase": "runtime"}], "name": "ruby25", "version": "2.5"}, {"images": [{"command":
    "bundle install --gemfile=$KUBELESS_DEPS_FILE --path=$KUBELESS_INSTALL_VOLUME",
    "image": "bitnami/ruby:2.6", "phase": "installation"}, {"env": {"GEM_HOME": "$(KUBELESS_INSTALL_VOLUME)/ruby/2.6.0"},
    "image": "kubeless/ruby@sha256:6a79d335bec224d820f149a6eb293e2bbab333ad63581e747ec644fd1af19c61",
    "phase": "runtime"}], "name": "ruby26", "version": "2.6"}]}, {"ID": "jvm", "depName":
    "", "fileNameSuffix": ".jar", "versions": [{"images": [{"command": "mv /kubeless/*
    /kubeless/payload.jar && cp /opt/*.jar /kubeless/ > /dev/termination-log 2>&1",
    "image": "caraboides/jvm-init@sha256:e57dbf3f56570a196d68bce1c0695102b2dbe3ae2ca6d1c704476a7a11542f1d",
    "phase": "compilation"}, {"image": "caraboides/jvm@sha256:2870c4f48df4feb2ee7478a152b44840d781d4b1380ad3fa44b3c7ff314faded",
    "phase": "runtime"}], "name": "jvm1.8", "version": "1.8"}]}, {"ID": "nodejs_distroless",
    "depName": "package.json", "fileNameSuffix": ".js", "versions": [{"images": [{"command":
    "/kubeless-npm-install.sh", "image": "kubeless/nodejs@sha256:424add88dc2a7fdc45012593159794d59a6ea4aafadfffb632d21ae53b1d262b",
    "phase": "installation"}, {"env": {"NODE_PATH": "$(KUBELESS_INSTALL_VOLUME)/node_modules"},
    "image": "kubeless/nodejs-distroless@sha256:1fa0469c5520f4e08d89b1fafd2cacf03f098b96ea04997fa52bb9ef2a180fb3",
    "phase": "runtime"}], "name": "node8", "version": "8"}]}, {"ID": "nodejsCE", "depName":
    "package.json", "fileNameSuffix": ".js", "versions": [{"images": [{"command":
    "/kubeless-npm-install.sh", "image": "kubeless/nodejs@sha256:456d98f6f15588b21f5110facf1cc203065840d4c227afa61d17c6c1fa98b3b6",
    "phase": "installation"}, {"env": {"NODE_PATH": "$(KUBELESS_INSTALL_VOLUME)/node_modules"},
    "image": "andresmgot/nodejs-ce@sha256:708c265d22a8a1599e05da844d26bc63e2f66f859ffecd2fcb541ecac9c66780",
    "phase": "runtime"}], "name": "node8", "version": "8"}]}, {"ID": "vertx", "depName":
    "pom.xml", "fileNameSuffix": ".java", "versions": [{"images": [{"command": "/compile-function.sh",
    "image": "oscardovao/vertx-init@sha256:6665629b3239eb1d81654381b02c3dd4b87ddb0a1b0b49acc165f0ff53264e0b",
    "phase": "compilation"}, {"image": "oscardovao/vertx@sha256:96243e5937a875422d6165e59f1fdb350f1a6d5befbd89f26968abea4345ade1",
    "phase": "runtime"}], "name": "vertx1.8", "version": "1.8"}]}]'
  service-type: ClusterIP
kind: ConfigMap
metadata:
  name: kubeless-config
  namespace: kubeless
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    kubeless: controller
  name: kubeless-controller-manager
  namespace: kubeless
spec:
  selector:
    matchLabels:
      kubeless: controller
  template:
    metadata:
      labels:
        kubeless: controller
    spec:
      containers:
      - env:
        - name: KUBELESS_INGRESS_ENABLED
          valueFrom:
            configMapKeyRef:
              key: ingress-enabled
              name: kubeless-config
        - name: KUBELESS_SERVICE_TYPE
          valueFrom:
            configMapKeyRef:
              key: service-type
              name: kubeless-config
        - name: KUBELESS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBELESS_CONFIG
          value: kubeless-config
        image: kubeless/function-controller:v1.0.4
        imagePullPolicy: IfNotPresent
        name: kubeless-function-controller
      - env:
        - name: KUBELESS_INGRESS_ENABLED
          valueFrom:
            configMapKeyRef:
              key: ingress-enabled
              name: kubeless-config
        - name: KUBELESS_SERVICE_TYPE
          valueFrom:
            configMapKeyRef:
              key: service-type
              name: kubeless-config
        - name: KUBELESS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBELESS_CONFIG
          value: kubeless-config
        image: kubeless/http-trigger-controller:v1.0.1
        imagePullPolicy: IfNotPresent
        name: http-trigger-controller
      - env:
        - name: KUBELESS_INGRESS_ENABLED
          valueFrom:
            configMapKeyRef:
              key: ingress-enabled
              name: kubeless-config
        - name: KUBELESS_SERVICE_TYPE
          valueFrom:
            configMapKeyRef:
              key: service-type
              name: kubeless-config
        - name: KUBELESS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBELESS_CONFIG
          value: kubeless-config
        image: kubeless/cronjob-trigger-controller:v1.0.1
        imagePullPolicy: IfNotPresent
        name: cronjob-trigger-controller
      serviceAccountName: controller-acct
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-acct
  namespace: kubeless
