apiVersion: v1
kind: Service
metadata:
   name: frontend-service
spec:
   selector:
     app: frontend-app
   type: NodePort
   ports:
   - name: web
     protocol: TCP
     port: 80  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: frontend-deployment
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: frontend-app
    spec: 
      containers:
        - name: angular-app
          image: kchandrakant/frontend:angular-app
          ports: 
            - 
              containerPort: 80