apiVersion: v1
kind: Pod
metadata:
   name: e2e-app
   labels:
     app: e2e-app
spec:
   containers:
     - name: angular-app
       image: kchandrakant/myrepo:angular-app
       ports:
         - containerPort: 4200