apiVersion: v1
kind: Service
metadata:
   name: e2e-service
spec:
   selector:
     app: e2e-app
   type: NodePort
   ports:
   - name: web
     protocol: TCP
     port: 4200  
   - name: api
     protocol: TCP
     port: 8085
   - name: db
     protocol: TCP
     port: 27017