version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    command: mongod --bind_ip 0.0.0.0
    volumes:
      - data-mongo:/data/db

  api:
    image: kchandrakant/backend:node-mongo-app
    environment:
     - MONGODB=mongodb://host.docker.internal/vocabulary
    #build: ../node-mongo-app
    ports:
     - 8085:8085
    depends_on:
     - db
     
  ui:
    #build: ../angular-app
    image: kchandrakant/frontend:angular-app
    ports:
     - 80:80
     
volumes:
  data-mongo: