FROM jenkins/jenkins:lts

RUN install-plugins.sh \
	pipeline-graph-analysis:1.9 \
    cloudbees-folder:6.7 \
    docker-commons:1.14 \
    jdk-tool:1.2 \
    script-security:1.56 \
    pipeline-rest-api:2.10 \
    command-launcher:1.3 \
    docker-workflow:1.18 \
    docker-plugin:1.1.6