#Global configurations
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['localhost:8085']
  - job_name: 'node-app'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['localhost:8085']